#!/usr/bin/env bash
# Mirror netbox-docker images from Docker Hub to quay.io/nmartins0611/
# and generate a docker-compose.override.yml pointing at the new registry.
#
# Usage:
#   ./mirror-to-quay.sh [--push] [--override]
#
#   --push      Pull, retag, and push images to quay.io/nmartins0611/
#   --override  Write docker-compose.override.yml with retagged image references
#
# Both flags can be combined. Without flags the script only prints what it would do.

set -euo pipefail

TARGET_REGISTRY="quay.io/nmartins0611"

# ---------------------------------------------------------------------------
# Images to mirror: source → flat target name under ${TARGET_REGISTRY}/
# quay.io only supports one level of namespace (org/repo), so names are flat.
# ---------------------------------------------------------------------------
declare -A IMAGES=(
  ["docker.io/netboxcommunity/netbox:v4.3-3.3.0"]="netbox:v4.3-3.3.0"
  ["docker.io/postgres:17-alpine"]="postgres:17-alpine"
  ["docker.io/valkey/valkey:8.1-alpine"]="valkey:8.1-alpine"
  # Build-time dependencies (only needed if you build the NetBox image locally)
  ["docker.io/ubuntu:24.04"]="ubuntu:24.04"
  ["ghcr.io/astral-sh/uv:0.7"]="uv:0.7"
)

DO_PUSH=false
DO_OVERRIDE=false

for arg in "$@"; do
  case "$arg" in
    --push)     DO_PUSH=true ;;
    --override) DO_OVERRIDE=true ;;
    --help|-h)
      sed -n '2,12p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      exit 1
      ;;
  esac
done

# ---------------------------------------------------------------------------
# Sanity check
# ---------------------------------------------------------------------------
if ! command -v docker &>/dev/null; then
  echo "❌ docker is not installed or not in PATH" >&2
  exit 1
fi

echo "===================================================================="
echo " Source → Target image map"
echo "===================================================================="
for src in "${!IMAGES[@]}"; do
  echo "  ${src}"
  echo "    → ${TARGET_REGISTRY}/${IMAGES[$src]}"
done
echo ""

if [[ "${DO_PUSH}" == false && "${DO_OVERRIDE}" == false ]]; then
  echo "ℹ️  Dry-run mode. Pass --push and/or --override to act."
  echo "    --push      pull + retag + push images to ${TARGET_REGISTRY}"
  echo "    --override  write docker-compose.override.yml"
  exit 0
fi

# ---------------------------------------------------------------------------
# Pull, retag, push
# ---------------------------------------------------------------------------
if [[ "${DO_PUSH}" == true ]]; then
  echo "===================================================================="
  echo " Logging in to quay.io"
  echo "===================================================================="
  docker login quay.io

  echo ""
  echo "===================================================================="
  echo " Pulling, retagging, and pushing images"
  echo "===================================================================="
  for src in "${!IMAGES[@]}"; do
    target="${TARGET_REGISTRY}/${IMAGES[$src]}"
    echo ""
    echo "▶ Pulling  : ${src}"
    docker pull "${src}"

    echo "▶ Retagging: ${src} → ${target}"
    docker tag "${src}" "${target}"

    echo "▶ Pushing  : ${target}"
    docker push "${target}"

    echo "✅ Done: ${target}"
  done
  echo ""
  echo "✅ All images pushed to ${TARGET_REGISTRY}"
fi

# ---------------------------------------------------------------------------
# Generate docker-compose.override.yml
# ---------------------------------------------------------------------------
if [[ "${DO_OVERRIDE}" == true ]]; then
  OVERRIDE_FILE="$(dirname "$0")/docker-compose.override.yml"

  echo ""
  echo "===================================================================="
  echo " Writing ${OVERRIDE_FILE}"
  echo "===================================================================="

  NETBOX_IMAGE="${TARGET_REGISTRY}/netbox:v4.3-3.3.0"
  POSTGRES_IMAGE="${TARGET_REGISTRY}/postgres:17-alpine"
  VALKEY_IMAGE="${TARGET_REGISTRY}/valkey:8.1-alpine"

  cat > "${OVERRIDE_FILE}" <<EOF
# Generated by mirror-to-quay.sh — points all services at ${TARGET_REGISTRY}
# Do not edit manually; re-run the script to regenerate.
services:
  netbox:
    image: ${NETBOX_IMAGE}
    ports:
      - "8000:8080"
  netbox-worker:
    image: ${NETBOX_IMAGE}
  netbox-housekeeping:
    image: ${NETBOX_IMAGE}
  postgres:
    image: ${POSTGRES_IMAGE}
  redis:
    image: ${VALKEY_IMAGE}
  redis-cache:
    image: ${VALKEY_IMAGE}
EOF

  echo "✅ Written: ${OVERRIDE_FILE}"
  echo ""
  echo "Preview:"
  echo "--------------------------------------------------------------------"
  cat "${OVERRIDE_FILE}"
fi
